services:
  wpsite:
    image: wordpress:6.8.2-php8.4-apache
    container_name: ${WPSITE_CONTAINER_NAME:-wordpress-site}
    restart: unless-stopped
    ports:
      - "${WPSITE_PORT:-8080}:80"
    environment:
      WORDPRESS_DB_HOST: ${WPDB_HOST:-db:3306}
      WORDPRESS_DB_USER: ${WPDB_USER:-wp_user}
      WORDPRESS_DB_PASSWORD: ${WPDB_PASSWORD:-wp_pass}
      WORDPRESS_DB_NAME: ${WPDB_NAME:-wordpress}
      WORDPRESS_CONFIG_EXTRA: |
        define('FS_METHOD','direct');
        define('WP_MEMORY_LIMIT','256M');
        define('WP_MAX_MEMORY_LIMIT','256M');
        define('WP_DEBUG', false);
    volumes:
      - ${WPSITE_VOLUME:-./volumes/wordpress}:/var/www/html
      - ./mount/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./mount/activationkey.php:/var/www/html/activationkey.php
    depends_on:
      - wpdb

  wpdb:
    image: mysql:9.4.0
    container_name: ${WPDB_CONTAINER_NAME:-wordpress-database}
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${WPDB_ROOT_PASSWORD:-rootpass}
      MYSQL_DATABASE: ${WPDB_NAME:-wordpress}
      MYSQL_USER: ${WPDB_USER:-wp_user}
      MYSQL_PASSWORD: ${WPDB_PASSWORD:-wp_pass}
    volumes:
      - ${WPDB_VOLUME:-./volumes/database}:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$${WPDB_ROOT_PASSWORD} --silent"]
      interval: 5s
      timeout: 3s
      retries: 20

  wpcli:
    image: wordpress:cli-2.6.0
    container_name: ${WPCLI_CONTAINER_NAME:-wordpress-cli}
    depends_on:
      - wpdb
      - wpsite
    user: "0:0" # this is REQUIRED to install plugins and themes
    environment:
      WP_CLI_ALLOW_ROOT: "1" # this is REQUIRED to install plugins and themes
      WORDPRESS_DB_HOST: ${WPDB_HOST:-db:3306}
      WORDPRESS_DB_USER: ${WPDB_USER:-wp_user}
      WORDPRESS_DB_PASSWORD: ${WPDB_PASSWORD:-wp_pass}
      WORDPRESS_DB_NAME: ${WPDB_NAME:-wordpress}
      MYSQL_ROOT_PASSWORD: ${WPDB_ROOT_PASSWORD:-rootpass}

      SITE_URL: ${WPCLI_SITE_URL:-http://localhost:8080}
      SITE_TITLE: ${WPCLI_SITE_TITLE:-My Awesome Site}
      WP_ADMIN_USER: ${WPCLI_ADMIN_USER:-admin}
      WP_ADMIN_PASSWORD: ${WPCLI_ADMIN_PASSWORD:-changeme123}
      WP_ADMIN_EMAIL: ${WPCLI_ADMIN_EMAIL:-admin@example.com}

      WP_PLUGINS: ${WPCLI_PLUGINS:-}
      WP_LOCALE: ${WPCLI_LOCALE:-zh_CN}
      WP_PERMALINK: ${WPCLI_PERMALINK:-/%postname%/}
      WP_TIMEZONE: ${WPCLI_TIMEZONE:-Asia/Shanghai}
    volumes:
      - ${WPSITE_VOLUME:-./volumes/wordpress}:/var/www/html
      - ./bootstrap:/scripts:ro
      - ./mount/plugins:/wp-plugins:ro
      - ./mount/themes:/wp-themes:ro
    entrypoint: [ "bash", "/scripts/wp-init.sh" ]
    restart: "no"
